.github/workflows/build_docs.yaml

Using a dedicated token to push the generated docs
No

fix: use dedicated token to push the generated docs

---

internal/version/version.go

Changing version from const to var so it can be mutated in compile time.
fixes #25

fix: const can not be updated in compile time

---

README.md
cmd/analyze.go
cmd/common_options/common_options.go
internal/clients/github/client.go

This pull request adds support for GitHub Enterprise instance (#10).
You can run legitify against a GitHub Enterprise instance if you set the endpoint URL in the environment variable ``GITHUB_ENDPOINT``:
```sh
export GITHUB_ENDPOINT="https://github.example.com/"
GITHUB_TOKEN=<your_token> legitify analyze --org org1,org2 --namespaces organization,member
```
resolves #10

feat: Added support for GitHub Enterprise instances (#10).

---

cmd/analyze.go

Avoid cache initialization in NewClient.
Running with big organization and GH latency may result in a long load-time before the initial "collecting metadata" print.
No

fix: lazy fill cache to avoid delays before printing starts

---

cmd/common_args.go

Quickfix: help message for SERVER_URL contains GITHUB_ENDPOINT

fix: SERVER_URL help message

---

README.md

Hi 👋 . This PR just intends to fix the example description for `--namespace` option. I believe the option name is singular, though it can take multiple items.
**from execution**
```
$ legitify analyze --org sample-org-1 --namespaces organization,member
___      _______  _______  ___   _______  ___   _______  __   __
|   |    |       ||       ||   | |       ||   | |       ||  | |  |
|   |    |    ___||    ___||   | |_     _||   | |    ___||  |_|  |
|   |    |   |___ |   | __ |   |   |   |  |   | |   |___ |       |
|   |___ |    ___||   ||  ||   |   |   |  |   | |    ___||_     _|
|       ||   |___ |   |_| ||   |   |   |  |   | |   |      |   |
|_______||_______||_______||___|   |___|  |___| |___|      |___|
By Legit Security
Error: unknown flag: --namespaces
2022/11/24 20:17:06 error …
```

docs: Fix typo in analyze-namespace option in the README

---

policies/github/actions.rego
policies/github/repository.rego

Hi 👋 . This PR tries to remove the duplicated numbering shown as part of the `remediationSteps` (ex. `1. 1. Make sure you have admin permissions`).
Some `.rego` file definitions include explicit numbering (`1.`), but I believe these numbers are automatically assigned from the array definition (other rules don't have explicit numbering).
**Before**
```
$ go run main.go analyze --org sample-org-1 --namespace repository
...
Workflows Are Allowed To Approve Pull Requests
----------------------------------------------
Your default GitHub Actions configuration allows for workflows to approve pull requests. This could allow users to bypass code-review restrictions.
Policy Name: data.repository.actions_can_approve_pull_requests
Namespace: repository
Severity: HIGH
Remediation Steps:
1. 1. Make …
```

fix: Remove duplicated numbering in the remediationSteps

---

internal/collected/github/repository.go

Removed the 'block_creations' field from the graphQL request since it's not supported in old GH versions, and we don't have a policy for it
https://github.com/Legit-Labs/legitify/issues/42

fix: removed the 'blocks_creations' field

---

cmd/analyze_executor.go
cmd/color.go
cmd/progressbar/progressbar.go
cmd/tty/tty.go
internal/collectors/collectors_manager/collectors_manager.go
internal/outputer/scheme/scheme.go

- disable progress bar when stderr is not a terminal
- bugfix: missing runner_group in output scheme priority map
- bugfix: reporting progress.Finished correctly for all bars 
no

fix: progress bar without terminal

---

.gitignore
Makefile

- Git ignore the generated /docs (docs/github, docs/gitlab) folders 
- Delete the docs/gitlab and docs/github folders on running `make clean`
Issue #142
- [ x] I have self-reviewed my changes before submitting the PR

fix: clean and ignore generated docs folder

---

README.md
go.mod
go.sum
internal/outputer/formatter/formatter_sarif.go
internal/outputer/formatter/formatter_sarif_test.go
internal/outputer/formatter/formatter_test/sarif_v2.1.0_schema.json
internal/outputer/formatter/output_format.go
internal/outputer/formatter/output_format_test.go
internal/outputer/formatter/policies_content.go

This pull request adds support for SARIF output to Legitify.
This PR closes #11. 
An example of the SARIF output produced by this feature can be seen [here](https://gist.github.com/chtzvt/eddb9614f7ddc8883ff6b2c868199d19). Microsoft provides [this nifty tool](https://microsoft.github.io/sarif-web-component/) if you'd like to parse/visualize the results.
This PR introduces a dependency on [`github.com/owenrumney/go-sarif/v2/sarif`](https://github.com/owenrumney/go-sarif).
_With ❤️ from [@XpiritBV](https://github.com/xpiritbv)._

feat: SARIF Output Support

---

README.md
internal/clients/gitlab/client.go
internal/collectors/gitlab/collection_context.go
internal/collectors/gitlab/group_collector.go
internal/collectors/gitlab/repository_collector.go
internal/collectors/gitlab/user_collector.go
internal/common/permissions/permissions.go
policies/gitlab/repository.rego

Skip failing repository policies when scanning gitlab free groups
https://github.com/Legit-Labs/legitify/issues/208

fix: skip failing policies when scanning gitlab free groups

---

go.mod
go.sum

upgrade the dependency of the secondary rate limit handler because GitHub changed the behavior of the API
No.

feat: upgrade secondary rate limit handler

---

.github/workflows/build_and_test.yaml
.regal/config.yaml
policies/github/actions.rego
policies/github/common/webhooks.rego
policies/github/enterprise.rego
policies/github/member.rego
policies/github/organization.rego
policies/github/repository.rego
policies/github/runner_group.rego
policies/gitlab/enterprise.rego
policies/gitlab/member.rego
policies/gitlab/organization.rego
policies/gitlab/repository.rego

This PR introduces [Regal](https://github.com/styrainc/regal) for linting the Rego files of the project. The Rego found here is generally in a good shape, so only a few rules have been either ignored or fixed. The few rules fixed include:
* [rule-shadows-builtin](https://docs.styra.com/regal/rules/bugs/rule-shadows-builtin) as there is already an `is_null` function in the standard lib
* [custom-has-key-construct](https://docs.styra.com/regal/rules/idiomatic/custom-has-key-construct) as this is handled by `object.keys` and `in` in modern Rego
* [use-assignment-operator](https://docs.styra.com/regal/rules/style/use-assignment-operator) as `:=` is preferred over `=` for rule assignment, and using this does not change the semantics of the code in any way.
Included is also a new job for …

policy: Add Regal for linting Rego

---

internal/collectors/github/repository_collector.go
policies/github/repository.rego

1. Added pagination to repository collaborators collector. Without it, it only returns 30 collaborators as it's a default per page.
2. Fixed typo in deletion protection rule check for repository rulesets. See [documentation](https://docs.github.com/en/rest/repos/rules?apiVersion=2022-11-28#get-rules-for-a-branch).

fix: Add pagination to collaborators collector

---

go.mod
go.sum

Upgrade go-github-ratelimit to v1.0.6 (handle new cases for secondary rate limit)
No

feat: upgrade go-github-ratelimit to v1.0.6

---

policies/github/enterprise.rego

Fix the policy title of "Enterprise Should Automatically Enable Secret Scanning Across All Organizations/Repositories"
No

docs: fix policy title

---

go.mod
go.sum
internal/clients/github/client.go
internal/clients/github/types/types.go
internal/collected/github/repository.go
policies/github/repository.rego

feat: added actors allowed to bypass policy

---

action.yml
action_examples/analyze_repos.yml

Updating docs and action examples to note that one must separate multiple repos with commas. 
no

docs: multiple repos separated by comma note

---

README.md
internal/collectors/github/repository_collector.go

feat: filter our archived repositories

---

internal/outputer/formatter/formatter_human.go

Preventing double-numbered lists from being printed, as first discussed [here](https://github.com/Legit-Labs/legitify/issues/312)

fix: Refactor human policy formatter

---

internal/outputer/formatter/formatter_human.go
internal/outputer/formatter/formatter_markdown.go
internal/outputer/formatter/formatter_sarif.go
internal/outputer/formatter/policies_content.go
policies/github/organization.rego

fix: dont add list prefix automatically for remediation steps

---

e2e/github_repository.go
internal/analyzers/skippers/skippers.go
internal/clients/github/client.go
internal/collected/github/repository.go
internal/collectors/collector.go
internal/collectors/github/repository_collector.go
internal/collectors/github/repository_context.go
policies/github/repository.rego
test/repository_test.go

* Add collection of 'Security and Analysis' settings for github repos

feat:  Add policy for detecting GitHub Secret-Scanning

---

policies/github/repository.rego
policies/gitlab/repository.rego

fix: Refine policy logic and enhance descriptions for forking restrictions

---

action.yml

Update the `action.yml` to resolve warnings around deprecated actions:
* Update node to use node 20 instead of node 16 (GitHub forces node 20 anyways)
* Update the setup-node action to v4
* Update `upload-sarif` action to v3 (v2 is being deprecated in December)
* Update `upload-artifact` action to v4 (v3 is being deprecated in November)
No - this is just maintenance that I noticed needs to be done to resolve warnings.

fix: Update action file to resolve warnings and upcoming deprecations

---

e2e/gitlab.go
policies/gitlab/repository.rego
test/repository_test.go

feat: adding override-variables policy
