Legit-Labs/legitify

README.md
docs/_config.yml
docs/index.md

Add important information to readme.md
no

docs: Update README.md

---

README.md

Adding introductory links to the readme.
No.

docs: add links to readme

---

.github/workflows/build_docs.yaml

The build docs workflow updates only the policies documentation instead of the whole site configuration.

fix: policy documentation generation.

---

internal/analyzers/analyzer.go

Fix a redundant tab according to gofmt.
No.

fix: gofmt

---

.goreleaser.yaml
go.mod

Used the correct key in the goreleaser configuration file

fix: fixed the goreleaser configuration file

---

policies/github/common/webhooks.rego
policies/github/organization.rego
policies/github/repository.rego
test/organization_test.go
test/repository_test.go

Changed severities and descriptions.

fix: align policies to legit

---

.github/CODEOWNERS

Add CODEOWNERS to restrict who can approve pull requests

feat: added CODEOWNERS

---

.github/workflows/build_and_lint.yaml
.github/workflows/build_docs.yaml
.github/workflows/release.yaml

- pin all dependencies
- request specific token permissions

fix: workflows security

---

cmd/analyze.go
cmd/list_orgs.go
cmd/list_repos.go
cmd/repositories_option.go
internal/clients/github/client.go
internal/collectors/collector_utils.go
internal/collectors/repository_collector.go
internal/collectors/repository_context.go
internal/common/types/types.go
internal/context_utils/utils.go
policies/github/repository.rego

1. Add --repo option to the analyze command to allow analyzing individual repositories
2. Add list repositories command
https://github.com/Legit-Labs/legitify/issues/16

feat: analyze individual repository

---

.github/workflows/release.yaml
.goreleaser.yaml

feat: add windows releases signing using osslsingcode

---

README.md
policies/github/actions.rego
policies/github/member.rego

- Adding actions threats
- Adding members threats
- Update readme
No

docs: Add actions and members threats and update readme

---

README.md
internal/clients/github/client.go
internal/collectors/repository_collector.go
internal/outputer/formatter/formatter_human.go
policies/github/organization.rego

docs: fix typos

---

.github/workflows/build_and_lint.yaml
.github/workflows/build_docs.yaml

GitHub actions dependencies
No

fix: updated actions dependencies

---

Dockerfile

Include common ca root certificates in legitify's container image
#32 
- [V] This PR follows the CONTRIBUTION.md guidelines
- [V] I have self-reviewed my changes before submitting the PR

fix: include common ca root certificates in legitify's container image

---

internal/collectors/collectors_manager.go

Fix progress bar creation when not specifying a namespace for analysis 
No

fix: progress bar when not specifying a namespace

---

go.mod
go.sum
internal/clients/github/client.go
internal/clients/github/types/types.go
internal/collected/github/organization_actions.go
internal/collected/github/repository.go
internal/collectors/actions_collector.go
internal/collectors/repository_collector.go
policies/github/actions.rego
policies/github/repository.rego
test/actions_test.go
test/repository_test.go

Added GitHub actions policies for the repository & actions namespaces.
https://github.com/Legit-Labs/legitify/issues/28

feat: policy GitHub actions default permissions

---

.github/prlint.json

What's being changed?
Allow for "policy: XXX" pull request titles
No

feat: added 'policy' to pr title

---

policies/github/runner_group.rego

added 'runner_group_not_limited_to_selected_repositories' policy
No

feat: added 'runner_group_not_limited_to_selected_repositories' policy

---

internal/collected/github/repository.go
internal/collectors/repository_collector.go
policies/github/repository.rego
test/repository_test.go

Separated the get deps graph API call to support gh versions that don't support it

fix: GHES intergration

---

.github/workflows/release.yaml
.goreleaser.yaml
README.md

Generate SLSA provenance for releases.
#36

feat: generate provenance for legitify release

---

README.md

missing line break in the readme. 
no

docs: missing line break in readme.

---

.github/workflows/build_and_lint.yaml
Makefile

fix: changed exclusion to be more explicit

---

README.md

fix slsa-verifier documentation
no

docs: fix slsa-verifier (legit-labs -> Legit-Labs)

---

.github/workflows/e2e_testing.yaml
Makefile

feat: added slack alerts

---

.github/workflows/build_docs.yaml

Fixed build_docs pipeline to allow building (but not publishing) for every pull request.

fix: changed build docs pipeline

---

cmd/docs.go
scripts/gen-gh-pages-docs.py

Generate jekyll for GitLab policies 
No

docs: support GitLab

---

.github/workflows/build_docs.yaml

Fix workflow to allow pulling from forks

fix: update build_docs.yaml

---

policies/github/repository.rego
policies/gitlab/repository.rego
test/actions_test.go
test/helpers.go
test/member_test.go
test/organization_test.go
test/repository_test.go
test/runner_group_test.go

Added unit tests and fixed bugs

fix: added repos unit tests and fixed policy bugs

---

internal/collected/gitlab_collected/repository.go
internal/collectors/gitlab/repository_collector.go
policies/gitlab/repository.rego
test/repository_test.go

Added pipeline status check policy
Added resolve threads policy

feat: add more gitlab repo policies

---

internal/collected/gitlab_collected/repository.go
internal/collectors/gitlab/repository_collector.go
policies/gitlab/repository.rego
test/repository_test.go

Added signed commits verification policy for gitlab

feat: added reject unsinged commits policy

---

.github/workflows/e2e_testing.yaml
e2e/e2e_test.go
internal/collectors/gitlab/repository_collector.go

feat: gitlab e2e tests

---

internal/analyzers/skippers/skippers.go
internal/clients/github/client.go
internal/collectors/collector.go
internal/collectors/github/repository_collector.go
internal/collectors/github/repository_context.go
policies/github/repository.rego

Mark specific branch protection rules as failed if branch protection is not enabled at all

fix: github branch protection policies

---

.github/workflows/e2e_testing.yaml
e2e/e2e_test.go
e2e/github_organization.go
e2e/github_repository.go
e2e/test_case.go
policies/github/repository.rego
test/repository_test.go

added e2e test for the GitHub repository policies
No

test: e2e for GitHub branch protection

---

e2e/e2e_test.go
internal/collected/gitlab_collected/repository.go
internal/collectors/gitlab/repository_collector.go
policies/gitlab/repository.rego
test/repository_test.go

Added Policies:
- Minimum required approvals
- Merge request authors may override the approvers list
- Repository Allows Review Requester To Approve Their Own Request
- Repository Dismiss Stale Reviews
- Repository Allows Committer Approvals Policy
- Code review is not limited to code-owners only

feat: add gitlab policies

---

cmd/analyze.go
cmd/analyze_executor.go
cmd/common_providers.go
cmd/inject_github.go
cmd/inject_gitlab.go
cmd/list_orgs.go
cmd/list_repos.go
cmd/progressbar/progressbar.go
cmd/root.go
cmd/utils.go
cmd/wire_gen.go
internal/analyzers/skippers/skippers.go
internal/clients/github/client.go
internal/collectors/permission_manager.go
internal/errlog/errlog.go
internal/screen/screen.go

add a hint to the screen when printing errors to the error.log

fix: error log hint

---

cmd/common_providers.go
e2e/e2e_test.go
e2e/test_case.go
internal/analyzers/skippers/skippers.go
internal/context_utils/utils.go
policies/gitlab/member.rego

test: gitlab e2e

---

docs/index.md

update docs to reflect GitLab support
No

docs: update docs to reflect gitlab support

---

internal/collectors/github/members_collector.go

Removed members collections from organization where no owner permission is found

feat: added owner condition

---

.github/workflows/build_docs.yaml

…ry as well
Updated the build-docs workflow to reflect changes in the docs root directory. before this change only changes in the policies was reflected
No

fix: build docs workflow

---

e2e/e2e_test.go

Making sure at least one entity satisfies the test condition
NO

fix: gitlab e2e

---

.github/workflows/release.yaml

updated release workflow to get new version of osslsigncode

fix: updated release workflow to get new version of osslsigncode

---

policies/github/repository.rego

Fix title, severity and remediation steps of pushes_are_not_restricted

fix: Rephrase policy pushes_are_not_restricted

---

Makefile
cmd/docs.go
docs/policies.md
scripts/gen-gh-pages-docs.py

- support threat as a simple string in rego yamls
- remove the top-level "Policies" directory from GitHub pages to fix the navigation bug
- 
No

fix: docs bugs

---

policies/github/actions.rego
policies/github/member.rego
policies/github/repository.rego
policies/github/runner_group.rego
policies/gitlab/member.rego
policies/gitlab/organization.rego
policies/gitlab/repository.rego

Fix titles without proper capitalization

fix: Titles capitalization

---

internal/analyzers/parsing_utils/utils.go

Threat not showing for some policies
No

fix: support simple string threat

---

docs/index.md

Rephrase supported SCMs and add a note with a link to the github page

docs: Update documantation's main page

---

README.md

feat: Update video

---

action.yml
action_examples/analyze_using_specific_version.yml

Update legitify base version in legitify's github action

feat: update legitify base version in github action

---

action.yml

feat: added branding to the action

---

cmd/root.go
index.js
internal/enricher/enrichers/enricher.go
internal/enricher/enrichers/hooks_list_enricher.go
internal/enricher/enrichers/members_list_enricher.go
internal/enricher/enrichers/scorecard_enricher.go
internal/outputer/formatter/colorizer.go
internal/outputer/formatter/common.go
internal/outputer/formatter/formatter_human.go
internal/outputer/formatter/formatter_human_test.go
internal/outputer/formatter/formatter_json.go
internal/outputer/formatter/formatter_json_test.go
internal/outputer/formatter/formatter_markdown.go
internal/outputer/formatter/formatter_markdown_test.go
internal/outputer/formatter/output_format.go
internal/outputer/formatter/output_format_test.go
internal/outputer/formatter/policies_content.go
internal/outputer/formatter/table_content.go
internal/outputer/formatter/theme.go

- add `--output-format markdown` to legitify
- change legitify action to use the makdown option and send output to job summary
- improve output for human-readable output 
#105

feat: markdown output

---

internal/outputer/formatter/table_content.go

Adding the word `legitify` to the title of the findings summary table.
Follow up on #105:
> It would be beneficial to include "Legitify" in the summary title, as there is another task with a similar title in our case.

feat: add legitify to the title of the summary table

---

CONTRIBUTING.md

Removing redundant contributing step 
No.

fix: update contributing.md

---

cmd/inject_github.go
cmd/inject_gitlab.go
cmd/wire_gen.go
internal/clients/github/client.go
internal/clients/github/transport/graphql.go
internal/clients/github/transport/secnodary_rate_limit.go
internal/clients/gitlab/client.go

- add support for secondary rate limit handling
- bugfix race condition causing multiple organizations collection during startup
#110

fix: add secondary rate limit handling

---

.github/workflows/release.yaml

Changed releaser workflow to get signed macos releases
An example to a release can be found here - https://github.com/noyna-org/legitify/releases/tag/v0.0.11

feat: added macos signature

---

.github/workflows/e2e_testing.yaml
internal/clients/pagination/mapper.go

Bugfix pagination (GitLab support)
no

fix: pagination

---

policies/gitlab/repository.rego

Convert the rego policies to be violated by default 
#84

feat: violate policies by default

---

CHANGELOG.md
CODE_OF_CONDUCT.md

* add missing contact details
* remove the unused changelog file
no

docs: add missing contact details and delete the unused changelog file

---

policies/github/actions.rego

violating actions policy by default.

feat: Convert the actions policies to be violated by default

---

policies/github/member.rego

violate  member policies by default

feat: Convert github member policies to be violated by default

---

policies/gitlab/organization.rego

violating gitlab org by default

feat: violating gitlab org by default

---

policies/github/organization.rego

feat: Convert gh org policies to be violated by default

---

policies/gitlab/member.rego

Converting GL member policies to be violated by default 

feat: Convert GL member policies to be violated by default 

---

policies/github/repository.rego
policies/gitlab/repository.rego
test/repository_test.go

Converting GH repository policies to be violated by default 

feat: Convert github repository policies to be violated by default 

---

policies/gitlab/repository.rego

violating gitlab repo by default

feat: violating gitlab repo by default

---

cmd/progressbar/progressbar.go
cmd/progressbar/update.go
internal/collectors/collector_utils.go
internal/gpt/analyzer.go

feat: better dynamic bar

---

cmd/progressbar/waiter.go
internal/clients/github/client.go
internal/clients/github/pagination/pagination.go
internal/clients/gitlab/client.go
internal/clients/gitlab/pagination/pagination.go
internal/clients/pagination/basic.go
internal/clients/pagination/mapper.go
internal/collectors/gitlab/repository_collector.go
internal/collectors/gitlab/user_collector.go
internal/common/types/types.go

- Fix pagination support when the list-options is the non-default one
- Fix running legitify as a GitLab site admin

fix: GitLab pagination and site admin

---

.github/workflows/release.yaml
.goreleaser.yaml

tap push using different token

fix: update tap token

---

.goreleaser.yaml

fix: removed syntax error

---

.github/workflows/release.yaml

changed sha calc location and referenced version in a different way 
release is not working properly

fix: changed sha calc location and referenced version in a different way

---

internal/clients/github/client.go
internal/collectors/github/repository_collector.go

making sure working group is waited in repository collection
https://github.com/Legit-Labs/legitify/issues/174

fix: make sure working group wait is called

---

README.md

Added information to the readme
No

docs: added gh extension to the readme

---

.github/workflows/build_and_lint.yaml
internal/gpt/analyzer.go

added the statuscheck action
https://github.com/Legit-Labs/legitify/issues/136

feat: added staticcheck action

---

.github/workflows/build_and_test.yaml
.github/workflows/code_analysis.yaml
README.md

feat: added code analysis badge

---

go.mod
go.sum

fix: updated golang.org/x/net

---

go.mod
go.sum
internal/clients/gitlab/client.go

removed gitlab app level cache
https://github.com/Legit-Labs/legitify/issues/130

fix: removed app level cache

---

README.md
cmd/analyze.go
cmd/common_args.go
cmd/inject_github.go
cmd/wire_gen.go
internal/clients/github/client.go
internal/collected/github/enterprise.go
internal/collectors/github/enterprise_collector.go
internal/collectors/github/enterprise_context.go
internal/collectors/github/runner_group_collector.go
internal/common/namespace/namespace.go
internal/common/permissions/permissions.go
policies/bundle_test.go
policies/github/enterprise.rego
test/enterprise_test.go

Added enterprise namespace
https://github.com/Legit-Labs/legitify/issues/181

feat: added the enterprise namespace

---

internal/clients/github/client.go
internal/collected/github/enterprise.go
policies/github/enterprise.rego

Adding more policies to the enterprise namespace

feat: adding enterprise policies

---

internal/clients/github/client.go
internal/collected/github/enterprise.go
policies/github/enterprise.rego

feat: added new enterprise policy

---

internal/clients/github/client.go

Added check if a user is a member of the enterprise

fix: added enterprise membership check

---

internal/collectors/github/actions_collector.go

Report change of actions collection for github earlier

fix: report actions progress earlier

---

README.md

feat: added scarf to the readme

---

.github/workflows/build_docs.yaml

updated build-docs workflow to run on 'workflow_dispatch' trigger
NO

feat: updated build-docs workflow to run on 'workflow_dispatch' trigger

---

.github/workflows/build_docs.yaml
policies/github/member.rego

Fix GitHub's admins count
Fixes Issue #204

fix: too many admins bug

---

.github/workflows/release.yaml

using legit.legitsecurity.com as the download source for brew installations
No

feat: update brew formula generation

---

.github/workflows/release.yaml

Fixed the package url when updating the brew formula
https://github.com/Legit-Labs/legitify/issues/211

fix: fixed release url

---

README.md
cmd/analyze.go
cmd/common_args.go
cmd/common_providers.go
internal/analyzers/skippers/skippers.go
internal/context_utils/utils.go

Added cli option for ignoring(skipping) specific policies
https://github.com/Legit-Labs/legitify/issues/214

feat: ignore policies

---

.github/workflows/release.yaml
scripts/gen-brew-multi-arch.py

Added script to update the brew formula. We couldn't use the goreleaser plugin because we are signing the executables and we couldn't use brew default bump pr because it does not support multi architectures. 
https://github.com/Legit-Labs/legitify/issues/186

feat: added script to create homebrew formula to support multi arch

---

.github/workflows/release.yaml
scripts/gen-brew-multi-arch.py

fix: brew multi arch wrong env variable

---

scripts/gen-brew-multi-arch.py

fix: added name and mail to global config

---

scripts/gen-brew-multi-arch.py

fix: requests and git config command

---

scripts/gen-brew-multi-arch.py

fix: fixed format

---

README.md
cmd/common_args.go
internal/clients/github/client.go
internal/clients/github/types/types.go
internal/collected/github/enterprise.go
policies/github/enterprise.rego

feat: chagned titles and added new policies

---

internal/clients/gitlab/client.go

fix: added better logging for gitlab namespaces

---

.github/workflows/e2e_testing.yaml
e2e/cli_commands.go
e2e/e2e_test.go
e2e/github_repository.go
e2e/gitlab.go
e2e/test_case.go

Added e2e test for cli commands, specifically various analyze flags
no
- [v] This PR follows the CONTRIBUTION.md guidelines
- [v] I have self-reviewed my changes before submitting the PR

feat: added e2e for analyze flags

---

internal/clients/gitlab/client.go

Use group base name to search for namespaces
https://github.com/Legit-Labs/legitify/issues/222

fix: GitLab Premium Collection

---

action.yml

Customize Legitify's action analysis results' artifact name.
Issue #241

feat: Customize legitify's action results artifact name

---

.github/workflows/e2e_testing.yaml
README.md
cmd/common_args.go

refactor: renamed LEGITIFY_TOKEN to SCM_TOKEN

---

README.md
action.yml
index.js

…by the user
- Added support for skipping policies in Legitify GitHub Action
- Added support for providing arbitrary parameters to the action
- Updated the base version to v1.0
https://github.com/Legit-Labs/legitify/issues/240

feat: support for ignore policies in the action

---

cmd/repositories_option.go

https://github.com/Legit-Labs/legitify/issues/243

fix: support scanning nested projects in GitLab

---

internal/outputer/formatter/formatter_sarif.go

https://github.com/Legit-Labs/legitify/issues/249

fix: include only failed entities in sarif

---

index.js

https://github.com/Legit-Labs/legitify/issues/247

fix: action extra param

---

.github/workflows/build_and_test.yaml
internal/clients/gitlab/client.go

- https://github.com/Legit-Labs/legitify/issues/250

fix: compare full path to support nested groups

---

cmd/common_args.go
cmd/root.go
cmd/version.go
internal/version/version.go
scripts/gen-gh-pages-docs.py

docs: added cli text

---

internal/collectors/github/members_collector.go
policies/github/member.rego

Instead of removing collaborators we don't have access to pass them through
- https://github.com/Legit-Labs/legitify/issues/256

fix: too many organization owners policy

---

internal/collectors/collectors_manager/collectors_manager.go

fix: fixed collectors manager writing to error log

---

.github/workflows/build_docs.yaml

fix: added email to docs push

---

cmd/analyze.go
cmd/common_args.go

docs: print only on analyze command

---

policies/gitlab/organization.rego

feat: Added new policy to GitLab groups: MFA grace period

---

internal/clients/gitlab/client.go
internal/collectors/gitlab/group_collector.go
internal/collectors/gitlab/repository_collector.go
internal/collectors/gitlab/user_collector.go

https://github.com/Legit-Labs/legitify/issues/287

fix: check root namespace

---

policies/github/actions.rego

fix: Updated a policy's description to match GitHub defaults

---

index.js
internal/common/namespace/namespace.go

fix: legitify action

---

.github/workflows/release.yaml
docs/CNAME

fix: goreleaser changed --rm-dist to --clean

---

cmd/common_args.go

fix: Utilize the valid permissions output file path from flag

---

.github/workflows/e2e_testing.yaml

feat: remove label after test
